//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public long MovieId { get; set; }
        public int LanguageId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<short> ReleaseYear { get; set; }
        public Nullable<short> rental_duaration { get; set; }
        public Nullable<decimal> rental_rate { get; set; }
        public Nullable<short> Length { get; set; }
        public Nullable<int> RatingId { get; set; }
        public string Summary { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
