//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieRentalModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public int RentalId { get; set; }
        public int InventoryId { get; set; }
        public int CustomerId { get; set; }
        public int Amount { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<System.DateTime> RentedOn { get; set; }
        public System.DateTime RentalValidUntil { get; set; }
        public System.DateTime CreatedOn { get; set; }
    }
}
